// ═══════════════════════════════════════════════════════════════════════════
// C1: differential test — deriveProposalStatus vs DAOShip.state()
//
// The client reimplements the contract's status machine in TypeScript so the UI
// can label a proposal without an RPC round-trip per row. Where the two
// disagree, the app shows a confident verdict the chain does not share, and the
// processProposal call that follows reverts: a Defeated proposal must be closed
// with '0x', a Ready one needs its original action bytes.
//
// governanceParity.test.ts already covers this — with fixtures a human wrote.
// Those prove the implementation matches someone's belief about the contract.
// This proves it matches the contract.
//
// The corpus is generated by daoships-contracts/scripts/gen-state-corpus.ts,
// which drives real proposals through every reachable state on a local chain and
// records what state() actually returned. Regenerate it after any change to
// state() or _didProposalPass():
//
//     cd ../daoships-contracts && npx hardhat run scripts/gen-state-corpus.ts
//     cp test/fixtures/state-corpus.json \
//        ../daoships-app/src/types/__tests__/fixtures/state-corpus.json
//
// Replaying a snapshot rather than calling a node keeps this suite offline and
// deterministic — see deployments.onchain.test.ts for the opt-in live checks.
// ═══════════════════════════════════════════════════════════════════════════
import { describe, it, expect, afterEach, vi } from 'vitest'
import { deriveProposalStatus, ProposalStatus, type Proposal } from '../proposal'
import type { DaoExpiryConfig } from '../dao'
import corpus from './fixtures/state-corpus.json'

/** DAOShip.sol enum name → the client's ProposalStatus. */
const EXPECTED: Record<string, ProposalStatus> = {
  Unborn: ProposalStatus.Unborn,
  Submitted: ProposalStatus.Submitted,
  Voting: ProposalStatus.Voting,
  Cancelled: ProposalStatus.Cancelled,
  Grace: ProposalStatus.Grace,
  Ready: ProposalStatus.Ready,
  Processed: ProposalStatus.Processed,
  Defeated: ProposalStatus.Defeated,
  Expired: ProposalStatus.Expired,
}

interface CorpusCase {
  label: string
  evaluatedAt: string
  onChainState: string
  row: Record<string, unknown>
  config: {
    voting_period: number
    grace_period: number
    quorum_percent: string
    default_expiry_window: number
  }
}

const allCases = corpus.cases as unknown as CorpusCase[]

/**
 * Unborn is out of scope for the client predicate, and that is correct rather
 * than a gap. `state()` answers "does this proposal exist and where is it";
 * deriveProposalStatus answers only the second half, because it is handed an
 * indexer row and a nonexistent proposal has no row. Existence is decided
 * upstream by whether the query returned anything.
 */
const cases = allCases.filter((c) => c.onChainState !== 'Unborn')

/**
 * Build the indexer row the client would have seen.
 *
 * The corpus only carries the fields deriveProposalStatus reads; everything else
 * is filler so the object satisfies Proposal.
 */
function toProposal(c: CorpusCase): Proposal {
  return {
    id: `0xdao-1`,
    dao_id: '0xdao',
    proposal_id: 1,
    created_at: new Date(0).toISOString(),
    submitter: null,
    tx_hash: '',
    proposal_data_hash: '0x',
    ...c.row,
  } as unknown as Proposal
}

function toConfig(c: CorpusCase): DaoExpiryConfig {
  return {
    voting_period: c.config.voting_period,
    grace_period: c.config.grace_period,
    default_expiry_window: c.config.default_expiry_window,
    quorum_percent: c.config.quorum_percent,
  } as DaoExpiryConfig
}

/**
 * Replay at exactly the block timestamp the chain answered at.
 *
 * The phase branches are timestamp comparisons, so "now" is an input to the
 * predicate, not context. An earlier version of this test derived a plausible
 * "now" from the recorded deadlines and reported a false failure on the Grace
 * case: it anchored one second before votingEnds, which really is still Voting.
 * The chain's own clock is the only defensible choice.
 */
function freezeNowAt(c: CorpusCase): void {
  vi.useFakeTimers()
  vi.setSystemTime(new Date(c.evaluatedAt))
}

afterEach(() => {
  vi.useRealTimers()
})

describe('deriveProposalStatus matches DAOShip.state()', () => {
  it('has a corpus covering every on-chain state the client can see', () => {
    const seen = new Set(cases.map((c) => c.onChainState))
    const inScope = Object.keys(EXPECTED).filter((s) => s !== 'Unborn')
    expect([...seen].sort()).toEqual(inScope.sort())
  })

  it('still records the Unborn case, even though the client cannot reach it', () => {
    expect(allCases.some((c) => c.onChainState === 'Unborn')).toBe(true)
  })

  it.each(cases.map((c) => [c.onChainState, c.label, c] as const))(
    'state()=%s — %s',
    (onChainState, _label, c) => {
      freezeNowAt(c)
      const actual = deriveProposalStatus(toProposal(c), toConfig(c))
      expect(actual, `chain said ${onChainState}`).toBe(EXPECTED[onChainState])
    },
  )
})

describe('the terminal branches, independent of clock anchoring', () => {
  // cancelled/processed are read straight off the status flags, so these must
  // hold at any "now" — a clock-dependent answer here would be a bug.
  const flagDriven = cases.filter((c) => ['Cancelled', 'Processed'].includes(c.onChainState))

  it.each(flagDriven.map((c) => [c.onChainState, c] as const))(
    '%s is independent of the current time',
    (onChainState, c) => {
      for (const t of [0, Date.parse('2000-01-01'), Date.parse('2999-01-01')]) {
        vi.useFakeTimers()
        vi.setSystemTime(new Date(t))
        expect(deriveProposalStatus(toProposal(c), toConfig(c))).toBe(EXPECTED[onChainState])
        vi.useRealTimers()
      }
    },
  )
})
